[project]
name = "json-path"
version = "0.1.0"
description = "Find the path of a key / value in a JSON hierarchy easily"
authors = ["Jabba Laci <jabba.laci@gmail.com>"]
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.15.0",
]
